name: manage-azure-policy-e3f1cc02
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/MFA_should_be_enabled_on_accounts_with_owner_permissions_on_your_subscription_aa633080-8b72-40c4-a2d7-d00c03e80bed/**'
#      - .github/workflows/manage-azure-policy-e3f1cc02.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_e3f1cc02}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/MFA_should_be_enabled_on_accounts_with_owner_permissions_on_your_subscription_aa633080-8b72-40c4-a2d7-d00c03e80bed/**
